# Generated by Django 4.1.7 on 2023-03-30 18:46

from django.db import migrations, models
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climbinghold',
            name='angle',
            field=models.IntegerField(blank=True, help_text='Angle of the hold, if applicable', null=True, verbose_name='angle'),
        ),
        migrations.AlterField(
            model_name='climbinghold',
            name='depth',
            field=django_measurement.models.MeasurementField(blank=True, help_text='Depth of the hold, if applicable', measurement=measurement.measures.distance.Distance, null=True, verbose_name='depth'),
        ),
        migrations.AlterField(
            model_name='climbinghold',
            name='size',
            field=django_measurement.models.MeasurementField(blank=True, help_text='Size of the edge, pocket, or other dimensions as applicable', measurement=measurement.measures.distance.Distance, null=True, verbose_name='size'),
        ),
    ]
