# Generated by Django 4.1.7 on 2023-03-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0002_alter_climbinghold_angle_alter_climbinghold_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='climbingequipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='climbing_equipment/', verbose_name='image'),
        ),
    ]
