# Generated by Django 4.1.7 on 2023-03-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0004_exercise_exerciseset_finger_hand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseset',
            name='fingers',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='hands',
        ),
        migrations.AlterField(
            model_name='exercisehandconfiguration',
            name='hand',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='exercisesethandconfiguration',
            name='hand',
            field=models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Both', 'Both')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Hand',
        ),
    ]
