# Generated by Django 4.1.7 on 2023-03-30 20:49

from django.db import migrations, models
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0005_remove_exerciseset_fingers_remove_exerciseset_hands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='effort',
            field=models.CharField(choices=[('1', 'Very easy'), ('2', 'Easy'), ('3', 'Moderate'), ('4', 'Hard'), ('5', 'Very hard')], default='M', max_length=10, verbose_name='effort'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='reps',
            field=models.PositiveIntegerField(default=1, verbose_name='reps'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='hold_duration',
            field=models.FloatField(blank=True, help_text='in seconds', null=True, verbose_name='hold duration'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=django_measurement.models.MeasurementField(default=0, measurement=measurement.measures.mass.Mass, verbose_name='weight'),
        ),
    ]
