# Generated by Django 4.1.7 on 2023-03-30 20:51

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0006_exerciseset_effort_exerciseset_reps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='weight',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass, verbose_name='weight'),
        ),
    ]
