# Generated by Django 4.1.7 on 2023-03-31 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0007_alter_exerciseset_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesethandconfiguration',
            name='exercise_set',
        ),
        migrations.RemoveField(
            model_name='exercisesethandconfiguration',
            name='fingers',
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'exercise', 'verbose_name_plural': 'exercises'},
        ),
        migrations.AddField(
            model_name='exercise',
            name='climbing_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hold.climbinghold'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hold.climbingequipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='left_index_finger',
            field=models.BooleanField(default=True, verbose_name='left index finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='left_middle_finger',
            field=models.BooleanField(default=True, verbose_name='left middle finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='left_pinky_finger',
            field=models.BooleanField(default=True, verbose_name='left pinky finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='left_ring_finger',
            field=models.BooleanField(default=True, verbose_name='left ring finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='left_thumb',
            field=models.BooleanField(default=False, verbose_name='left thumb'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_index_finger',
            field=models.BooleanField(default=True, verbose_name='right index finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_middle_finger',
            field=models.BooleanField(default=True, verbose_name='right middle finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_pinky_finger',
            field=models.BooleanField(default=True, verbose_name='right pinky finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_ring_finger',
            field=models.BooleanField(default=True, verbose_name='right ring finger'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='right_thumb',
            field=models.BooleanField(default=False, verbose_name='right thumb'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_index_finger',
            field=models.BooleanField(default=True, verbose_name='left index finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_middle_finger',
            field=models.BooleanField(default=True, verbose_name='left middle finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_pinky_finger',
            field=models.BooleanField(default=True, verbose_name='left pinky finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_ring_finger',
            field=models.BooleanField(default=True, verbose_name='left ring finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_thumb',
            field=models.BooleanField(default=False, verbose_name='left thumb'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_index_finger',
            field=models.BooleanField(default=True, verbose_name='right index finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_middle_finger',
            field=models.BooleanField(default=True, verbose_name='right middle finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_pinky_finger',
            field=models.BooleanField(default=True, verbose_name='right pinky finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_ring_finger',
            field=models.BooleanField(default=True, verbose_name='right ring finger'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_thumb',
            field=models.BooleanField(default=False, verbose_name='right thumb'),
        ),
        migrations.DeleteModel(
            name='ExerciseHandConfiguration',
        ),
        migrations.DeleteModel(
            name='ExerciseSetHandConfiguration',
        ),
        migrations.DeleteModel(
            name='Finger',
        ),
    ]
