# Generated by Django 4.1.7 on 2023-04-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0009_exerciseset_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('thumb', 'Thumb'), ('index', 'Index'), ('middle', 'Middle'), ('ring', 'Ring'), ('pinky', 'Pinky')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='left_index_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='left_middle_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='left_pinky_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='left_ring_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='left_thumb',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_index_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_middle_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_pinky_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_ring_finger',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='right_thumb',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='left_index_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='left_middle_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='left_pinky_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='left_ring_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='left_thumb',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='right_index_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='right_middle_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='right_pinky_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='right_ring_finger',
        ),
        migrations.RemoveField(
            model_name='exerciseset',
            name='right_thumb',
        ),
        migrations.CreateModel(
            name='GripPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grip_type', models.CharField(choices=[('DC', 'Drag Crimp'), ('HFC', 'Half Crimp'), ('F', 'Full Crimp'), ('S', 'Sloper'), ('P', 'Pinch'), ('J', 'Jug')], max_length=3)),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='grip_positions/', verbose_name='image')),
                ('fingers', models.ManyToManyField(limit_choices_to={'name__in': [('thumb', 'Thumb'), ('index', 'Index'), ('middle', 'Middle'), ('ring', 'Ring'), ('pinky', 'Pinky')]}, related_name='grip_positions', to='hold.finger')),
            ],
            options={
                'verbose_name': 'Grip Position',
                'verbose_name_plural': 'Grip Positions',
            },
        ),
    ]
