# Generated by Django 4.1.7 on 2023-04-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0010_finger_remove_exercise_left_index_finger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gripposition',
            name='description',
        ),
        migrations.AlterField(
            model_name='gripposition',
            name='fingers',
            field=models.ManyToManyField(related_name='grip_positions', to='hold.finger'),
        ),
    ]
