# Generated by Django 4.1.7 on 2023-04-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0011_remove_gripposition_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Grip Type',
                'verbose_name_plural': 'Grip Types',
            },
        ),
        migrations.RemoveField(
            model_name='gripposition',
            name='grip_type',
        ),
    ]
