# Generated by Django 4.1.7 on 2023-04-02 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0012_griptype_remove_gripposition_grip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gripposition',
            name='grip_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hold.griptype'),
            preserve_default=False,
        ),
    ]
