# Generated by Django 4.1.7 on 2023-04-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hold', '0013_gripposition_grip_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='climbing_hold',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='climbing_hold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hold.climbinghold'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='equipment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hold.climbingequipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='left_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_hand_grip_position', to='hold.gripposition'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='right_hand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_hand_grip_position', to='hold.gripposition'),
        ),
    ]
