# Generated by Django 4.1.7 on 2023-03-30 20:21

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='body_weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
